#!/usr/bin/env node
// PreToolUse hook: blocks direct edits to generated files, pointing to the real source.
// Runtime-agnostic: handles Claude Code and GitHub Copilot (VS Code / CLI) payloads.

const fs = require("fs");

const GENERATED = [
  [
    "Sources/Navigator/EPUB/Assets/Static/scripts/",
    "This file is generated from Sources/Navigator/EPUB/Scripts/src/. Edit the sources there, then run `make scripts` to rebundle.",
  ],
  [
    "Support/CocoaPods/",
    "The podspecs are generated. Run `make podspecs` instead of editing them.",
  ],
  [
    "Playground/Playground.xcodeproj/",
    "The Playground project is generated by XcodeGen. Edit Playground/project.yml, then run `make playground`.",
  ],
];

// Tool input lives under different keys across agents.
function toolInput(data) {
  return data.tool_input || data.toolArgs || data.tool_args || {};
}
// File path property name varies: file_path (Claude), filePath (VS Code), path (Copilot CLI).
function filePath(input) {
  return input.file_path || input.filePath || input.path || "";
}

function main() {
  let data;
  try {
    data = JSON.parse(fs.readFileSync(0, "utf8"));
  } catch {
    return;
  }
  const path = filePath(toolInput(data));
  for (const [fragment, reason] of GENERATED) {
    if (path.includes(fragment)) {
      process.stdout.write(
        JSON.stringify({
          hookSpecificOutput: {
            hookEventName: "PreToolUse",
            permissionDecision: "deny",
            permissionDecisionReason: reason,
          },
        }) + "\n"
      );
      return;
    }
  }
}

main();
process.exit(0);
