#!/usr/bin/env node
// PreToolUse hook: blocks direct edits to generated files, pointing to the real source.

const fs = require("fs");

const GENERATED = [
  [
    "Sources/Navigator/EPUB/Assets/Static/scripts/",
    "This file is generated from Sources/Navigator/EPUB/Scripts/src/. Edit the sources there, then run `make scripts` to rebundle.",
  ],
  [
    "Support/CocoaPods/",
    "The podspecs are generated. Run `make podspecs` instead of editing them.",
  ],
  [
    "Playground/Playground.xcodeproj/",
    "The Playground project is generated by XcodeGen. Edit Playground/project.yml, then run `make playground`.",
  ],
];

function main() {
  let data;
  try {
    data = JSON.parse(fs.readFileSync(0, "utf8"));
  } catch {
    return;
  }
  const path = (data.tool_input && data.tool_input.file_path) || "";
  for (const [fragment, reason] of GENERATED) {
    if (path.includes(fragment)) {
      process.stdout.write(
        JSON.stringify({
          hookSpecificOutput: {
            hookEventName: "PreToolUse",
            permissionDecision: "deny",
            permissionDecisionReason: reason,
          },
        }) + "\n"
      );
      return;
    }
  }
}

main();
process.exit(0);
